"""add_onnx_path_to_training_jobs

Revision ID: edb779c5d941
Revises: c3d4e5f6a7b8
Create Date: 2026-06-04 20:43:56.979047
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = 'edb779c5d941'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_jobs', sa.Column('onnx_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_jobs', 'onnx_path')
    # ### end Alembic commands ###
