/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const API_BASE: typeof import('./lib/constants').API_BASE
  const Activity: typeof import('react').Activity
  const BOX_COLORS: typeof import('./lib/constants').BOX_COLORS
  const BatchProgress: typeof import('./components/BatchProgress').BatchProgress
  const CANVAS_MAX_H: typeof import('./lib/constants').CANVAS_MAX_H
  const CANVAS_MAX_W: typeof import('./lib/constants').CANVAS_MAX_W
  const CANVAS_MIN_BOX_SIZE: typeof import('./lib/constants').CANVAS_MIN_BOX_SIZE
  const CategoryInput: typeof import('./components/CategoryInput').CategoryInput
  const DEFAULT_BATCH: typeof import('./lib/constants').DEFAULT_BATCH
  const DEFAULT_CONF: typeof import('./lib/constants').DEFAULT_CONF
  const DEFAULT_EPOCHS: typeof import('./lib/constants').DEFAULT_EPOCHS
  const DEFAULT_IMGSZ: typeof import('./lib/constants').DEFAULT_IMGSZ
  const DEFAULT_IOU: typeof import('./lib/constants').DEFAULT_IOU
  const DetectionCanvas: typeof import('./components/DetectionCanvas').DetectionCanvas
  const DetectionResult: typeof import('./components/DetectionResult').DetectionResult
  const DetectionSkeleton: typeof import('./components/LoadingSkeleton').DetectionSkeleton
  const ErrorBoundary: typeof import('./components/ErrorBoundary').ErrorBoundary
  const FilterPanel: typeof import('./components/FilterPanel').FilterPanel
  const Fragment: typeof import('react').Fragment
  const HistoryList: typeof import('./components/HistoryList').HistoryList
  const HistorySkeleton: typeof import('./components/LoadingSkeleton').HistorySkeleton
  const Home: typeof import('./pages/Home').Home
  const ImageUploader: typeof import('./components/ImageUploader').ImageUploader
  const KeyframeGrid: typeof import('./components/KeyframeGrid').KeyframeGrid
  const Layout: typeof import('./components/Layout').Layout
  const MAX_UPLOAD_SIZE_MB: typeof import('./lib/constants').MAX_UPLOAD_SIZE_MB
  const ModelSelector: typeof import('./components/ModelSelector').ModelSelector
  const QueryClient: typeof import('@tanstack/react-query').QueryClient
  const QueryClientProvider: typeof import('@tanstack/react-query').QueryClientProvider
  const ResultTable: typeof import('./components/ResultTable').ResultTable
  const Sidebar: typeof import('./components/Sidebar').Sidebar
  const Suspense: typeof import('react').Suspense
  const ThemeContext: typeof import('./hooks/useTheme').ThemeContext
  const ThemeProvider: typeof import('./components/ThemeProvider').ThemeProvider
  const TrainingPanel: typeof import('./components/TrainingPanel').TrainingPanel
  const ValidationSettings: typeof import('./components/ValidationSettings').ValidationSettings
  const VideoDetail: typeof import('./components/VideoDetail').VideoDetail
  const VideoPanel: typeof import('./components/VideoPanel').VideoPanel
  const VideoValidator: typeof import('./components/VideoValidator').VideoValidator
  const addBox: typeof import('./services/api').addBox
  const applyFilter: typeof import('./lib/filterBoxes').applyFilter
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const chartUrl: typeof import('./services/api').chartUrl
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const deleteBox: typeof import('./services/api').deleteBox
  const deleteDetection: typeof import('./services/api').deleteDetection
  const deleteTrainingJob: typeof import('./services/api').deleteTrainingJob
  const deleteVideo: typeof import('./services/api').deleteVideo
  const detectImage: typeof import('./services/api').detectImage
  const downloadBlob: typeof import('./services/api').downloadBlob
  const downloadDatasetBatch: typeof import('./services/api').downloadDatasetBatch
  const downloadDatasetUrl: typeof import('./services/api').downloadDatasetUrl
  const downloadModelUrl: typeof import('./services/api').downloadModelUrl
  const downloadOnnxUrl: typeof import('./services/api').downloadOnnxUrl
  const downloadYoloTxt: typeof import('./lib/yoloExport').downloadYoloTxt
  const exportBatch: typeof import('./services/api').exportBatch
  const exportSingleUrl: typeof import('./services/api').exportSingleUrl
  const extractKeyframes: typeof import('./services/api').extractKeyframes
  const fetchTrainingJobs: typeof import('./services/api').fetchTrainingJobs
  const fetchYoloSeries: typeof import('./services/api').fetchYoloSeries
  const formatTime: typeof import('./lib/formatTime').formatTime
  const forwardRef: typeof import('react').forwardRef
  const generateYoloTxt: typeof import('./lib/yoloExport').generateYoloTxt
  const getDetection: typeof import('./services/api').getDetection
  const getModelStatus: typeof import('./services/api').getModelStatus
  const getVideo: typeof import('./services/api').getVideo
  const keyframeImageUrl: typeof import('./services/api').keyframeImageUrl
  const lazy: typeof import('react').lazy
  const listDetections: typeof import('./services/api').listDetections
  const listVideos: typeof import('./services/api').listVideos
  const memo: typeof import('react').memo
  const parseCategories: typeof import('./lib/parsers').parseCategories
  const request: typeof import('./services/request').request
  const saveFilterSettings: typeof import('./services/api').saveFilterSettings
  const startTraining: typeof import('./services/api').startTraining
  const startTransition: typeof import('react').startTransition
  const toast: typeof import('react-hot-toast').toast
  const tokenCache: typeof import('./lib/constants').tokenCache
  const unloadModel: typeof import('./services/api').unloadModel
  const uploadCache: typeof import('./lib/constants').uploadCache
  const uploadVideo: typeof import('./services/api').uploadVideo
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useAntdTable: typeof import('ahooks').useAntdTable
  const useAsyncEffect: typeof import('ahooks').useAsyncEffect
  const useBatchDetection: typeof import('./hooks/useBatchDetection').useBatchDetection
  const useBoolean: typeof import('ahooks').useBoolean
  const useCallback: typeof import('react').useCallback
  const useClickAway: typeof import('ahooks').useClickAway
  const useContext: typeof import('react').useContext
  const useControllableValue: typeof import('ahooks').useControllableValue
  const useCookieState: typeof import('ahooks').useCookieState
  const useCountDown: typeof import('ahooks').useCountDown
  const useCounter: typeof import('ahooks').useCounter
  const useCreation: typeof import('ahooks').useCreation
  const useDebounce: typeof import('ahooks').useDebounce
  const useDebounceEffect: typeof import('ahooks').useDebounceEffect
  const useDebounceFn: typeof import('ahooks').useDebounceFn
  const useDebugValue: typeof import('react').useDebugValue
  const useDeepCompareEffect: typeof import('ahooks').useDeepCompareEffect
  const useDeepCompareLayoutEffect: typeof import('ahooks').useDeepCompareLayoutEffect
  const useDeferredValue: typeof import('react').useDeferredValue
  const useDeleteDetectionMutation: typeof import('./hooks/useDetection').useDeleteDetectionMutation
  const useDetectMutation: typeof import('./hooks/useDetection').useDetectMutation
  const useDetectionDetailQuery: typeof import('./hooks/useDetection').useDetectionDetailQuery
  const useDetectionListQuery: typeof import('./hooks/useDetection').useDetectionListQuery
  const useDocumentVisibility: typeof import('ahooks').useDocumentVisibility
  const useDrag: typeof import('ahooks').useDrag
  const useDrop: typeof import('ahooks').useDrop
  const useDynamicList: typeof import('ahooks').useDynamicList
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useEventEmitter: typeof import('ahooks').useEventEmitter
  const useEventListener: typeof import('ahooks').useEventListener
  const useEventTarget: typeof import('ahooks').useEventTarget
  const useExportBatchMutation: typeof import('./hooks/useDetection').useExportBatchMutation
  const useExternal: typeof import('ahooks').useExternal
  const useFavicon: typeof import('ahooks').useFavicon
  const useFocusWithin: typeof import('ahooks').useFocusWithin
  const useFullscreen: typeof import('ahooks').useFullscreen
  const useFusionTable: typeof import('ahooks').useFusionTable
  const useGetState: typeof import('ahooks').useGetState
  const useHistoryTravel: typeof import('ahooks').useHistoryTravel
  const useHomeState: typeof import('./hooks/useHomeState').useHomeState
  const useHover: typeof import('ahooks').useHover
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInViewport: typeof import('ahooks').useInViewport
  const useInfiniteQuery: typeof import('@tanstack/react-query').useInfiniteQuery
  const useInfiniteScroll: typeof import('ahooks').useInfiniteScroll
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useInterval: typeof import('ahooks').useInterval
  const useIsomorphicLayoutEffect: typeof import('ahooks').useIsomorphicLayoutEffect
  const useKeyPress: typeof import('ahooks').useKeyPress
  const useLatest: typeof import('ahooks').useLatest
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLocalStorageState: typeof import('ahooks').useLocalStorageState
  const useLockFn: typeof import('ahooks').useLockFn
  const useLongPress: typeof import('ahooks').useLongPress
  const useMap: typeof import('ahooks').useMap
  const useMemo: typeof import('react').useMemo
  const useMemoizedFn: typeof import('ahooks').useMemoizedFn
  const useMount: typeof import('ahooks').useMount
  const useMouse: typeof import('ahooks').useMouse
  const useMutation: typeof import('@tanstack/react-query').useMutation
  const useMutationObserver: typeof import('ahooks').useMutationObserver
  const useNetwork: typeof import('ahooks').useNetwork
  const useOptimistic: typeof import('react').useOptimistic
  const usePagination: typeof import('ahooks').usePagination
  const usePrevious: typeof import('ahooks').usePrevious
  const useQuery: typeof import('@tanstack/react-query').useQuery
  const useQueryClient: typeof import('@tanstack/react-query').useQueryClient
  const useRafInterval: typeof import('ahooks').useRafInterval
  const useRafState: typeof import('ahooks').useRafState
  const useRafTimeout: typeof import('ahooks').useRafTimeout
  const useReactive: typeof import('ahooks').useReactive
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRequest: typeof import('ahooks').useRequest
  const useResetState: typeof import('ahooks').useResetState
  const useResponsive: typeof import('ahooks').useResponsive
  const useSafeState: typeof import('ahooks').useSafeState
  const useScroll: typeof import('ahooks').useScroll
  const useSelections: typeof import('ahooks').useSelections
  const useSessionStorageState: typeof import('ahooks').useSessionStorageState
  const useSet: typeof import('ahooks').useSet
  const useSetState: typeof import('ahooks').useSetState
  const useSize: typeof import('ahooks').useSize
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTextSelection: typeof import('ahooks').useTextSelection
  const useTheme: typeof import('./hooks/useTheme').useTheme
  const useThrottle: typeof import('ahooks').useThrottle
  const useThrottleEffect: typeof import('ahooks').useThrottleEffect
  const useThrottleFn: typeof import('ahooks').useThrottleFn
  const useTimeout: typeof import('ahooks').useTimeout
  const useTitle: typeof import('ahooks').useTitle
  const useToggle: typeof import('ahooks').useToggle
  const useTrackedEffect: typeof import('ahooks').useTrackedEffect
  const useTransition: typeof import('react').useTransition
  const useTranslation: typeof import('react-i18next').useTranslation
  const useUnmount: typeof import('ahooks').useUnmount
  const useUnmountedRef: typeof import('ahooks').useUnmountedRef
  const useUpdate: typeof import('ahooks').useUpdate
  const useUpdateEffect: typeof import('ahooks').useUpdateEffect
  const useUpdateLayoutEffect: typeof import('ahooks').useUpdateLayoutEffect
  const useVirtualList: typeof import('ahooks').useVirtualList
  const useVirtualizer: typeof import('@tanstack/react-virtual').useVirtualizer
  const useWebSocket: typeof import('ahooks').useWebSocket
  const useWhyDidYouUpdate: typeof import('ahooks').useWhyDidYouUpdate
  const useYoloValidation: typeof import('./hooks/useYoloValidation').useYoloValidation
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ThemeMode, ThemeContextValue } from './hooks/useTheme'
  import('./hooks/useTheme')
  // @ts-ignore
  export type { ErrorBoundary } from './components/ErrorBoundary'
  import('./components/ErrorBoundary')
  // @ts-ignore
  export type { SidebarProps } from './components/Sidebar'
  import('./components/Sidebar')
  // @ts-ignore
  export type { FilterMode } from './lib/filterBoxes'
  import('./lib/filterBoxes')
  // @ts-ignore
  export type { YoloSeries } from './services/api'
  import('./services/api')
  // @ts-ignore
  export type { BBox, Detection, DetectResponse, TrainingJob, KeyFrame, VideoInfo, VideoList, ListResponse } from './types/index'
  import('./types/index')
}
